### ISSUE TITLE
Requesting capability to bootstrap with pre-existing but empty db

### ISSUE THREAD

**Issue by nneul** [zabbix/zabbix-community-docker#103]
Would like to see capability to init the system with the zabbix database already existing, but empty. This would be typical if you have an env setup where the db has been created and the app user has limited permissions to do anything to the db server itself.

I hacked this together just by running the sql content from within your container oimage, but it would be nice if you had something that would allow your config/init/bootstrap.sh to detect "database exists, but schema doesn't", as opposed to seeing that the database is there and immediately exiting.

**Comment by jangaraj** [comment]
Hi Nathan, I recommend creating a SQL file, which will handle empty Zabbix database (`CREATE TABLE IF NOT EXISTS ...`). Then use a volume to mount your SQL file into container file systems `/etc/zabbix/api/<optional_dir/><your_sql_file>.sql`. Bootstrap script will try to run that SQL script against configured Zabbix DB.

Example: see `02-create-regular-expressions.sql` in https://github.com/monitoringartist/dockbix-xxl/tree/master/Dockerfile/dockbix-xxl/container-files-dockbix-xxl/etc/zabbix/api. Plain SQL is used here to create regular expression because API for that is not available.

Feel free to improve doc about this feature https://github.com/monitoringartist/dockbix-xxl#xxl-api-features
