### ISSUE TITLE
Add dockerfile for zabbix-agent

### ISSUE THREAD

**Issue by xiaoping378** [zabbix/zabbix-community-docker#28]
Could you please add the dockerfile for zabbix-agent ?

**Comment by jangaraj** [comment]
It's easy to install and run zabbix-agent in the container. But your user
experience will be poor. You will not be to see all hosts metrics, because
container. If someone containerize zabbix agent (I don't prefer any
hackish, dirty source code modification), which will provide similar
functionality as standalone package, then I'll be happy to publish it here.

Meanwhile:
- new zabbix-3.0 docker image contains compiled zabbix agent as well -
  fortunately it's ok only for zabbix-server
- test some other community Github docker zabbix-agent projects:
  probably https://github.com/million12/docker-zabbix-agent is the best one
  at the moment

Jan Garaj

```
 Web: http://www.jangaraj.com
```

LinkedIn: http://www.linkedin.com/in/jangaraj

**Comment by xiaoping378** [comment]
Thanks, Got it.
