### ISSUE TITLE
Default installation is not working

### ISSUE THREAD

**Issue by fxpester** [zabbix/zabbix-community-docker#33]
Hi, I`m just learning Docker, choose Zabbix as a first try.

I copy your commands from - `Standard Dockerized Zabbix deployement`
Zabbix Server is ok, but no data received from agent.

now I check logs and see:
`996:20160311:101138.163 cannot send list of active checks to "127.0.0.1": host [Zabbix server] not monitored
` - From Server.

`1009:20160311:101338.190 no active checks on server [127.0.0.1:10051]: host [Zabbix server] not monitored
` - from Agent.

**Comment by jangaraj** [comment]
It's a Zabbix design. Try google `Zabbix cannot send list of active checks to` for more details and please read doc about active checks - https://www.zabbix.com/documentation/3.0/manual/appendix/items/activepassive. You need to configure it properly - please use community forum/IRC, because this not related to dockerized zabbix server.
