### ISSUE TITLE
Can the compose.yml run net: host mode ?

### ISSUE THREAD

**Issue by xiaoping378** [zabbix/zabbix-community-docker#38]
I doubt my performance issue is the network mode of docker,  when I changed bridge to be host, I met this output...

![issue](http://imglf0.nosdn0.126.net/img/d2MrSVhyNXpnb3pqcnlFZ1lyYzh2VFJEcnJNOWxRVlRvUHY5MG5WRkRyUGdYQlg4Y002b3dRPT0.png?imageView&thumbnail=500x0&quality=96&stripmeta=0&type=jpg)

it seems to be the SQL  don't support a lcoal user ?

**Comment by jangaraj** [comment]
Localhost in the container! = localhost in your host. Use regular IP and it
should be ok.

Jan Garaj

Email/IM: jan.garaj@gmail.com
   Mobile: +44 79 234 69004 (+421 949 113 911)
     Web: http://www.jangaraj.com / http://monitoringartist.com
LinkedIn: http://www.linkedin.com/in/jangaraj

**Comment by xiaoping378** [comment]
Thanks. I will try this.

**Comment by xiaoping378** [comment]
> Localhost in the container! = localhost in your host. 

you mean the bridge mode, right?

I have changed to --net = host

**Comment by xiaoping378** [comment]
zabbix-server run on the default network mode - bridge. 
it's throughout reduce 60% ???  refer to below link.
https://www.percona.com/blog/2016/02/05/measuring-docker-cpu-network-overhead/

**Comment by jangaraj** [comment]
I'm closing this problem, because it's not problem of Zabbix Docker image. You can use networking, which you like. Provided compose.yml is generic example and you can still customize it. There is a lot of issues around docker network performance, but again this is not in the scope of this project (basically problem is that docker proxy is in user space). Companies, which need really high network throughput (BBC, CloudFlare) are dropping any userspace components and they are doing all business logic in system space only - keyword "unikernel". I recommend to read some their blog posts. But you will need really deep knowledge about this problem.

**Comment by xiaoping378** [comment]
OK， Got it.
Thanks.
