### ISSUE TITLE
Correct alertscript permissions

### ISSUE THREAD

**Issue by pedropilla** [zabbix/zabbix-community-docker#64]
Hi, I was using 2.4 image and now migrating to 3.0, but the RUN CHMOD in my Dockerfile is not working.

In the dir "container-files" there's a usr/local/share/zabbix/alertscripts/telegram-ncat.sh

Here's the Dockerfile

```
ADD container-files /

RUN \
    chmod +x /usr/local/share/zabbix/alertscripts/telegram-ncat.sh

```

**Comment by jangaraj** [comment]
What it means "it's not working"? Which docker image:tag are you using?

IMHO creating of custom docker image just for one alert script is overkill. You need to rebuild your image, when new source image is released. Why you are not using volumes? Or even better why you don't create storage image/container only with your script and volume which will publish your script; then zabbix-server can use it as `volume-from`?

I'm closing this issue, because provided image can't cause your problem. It's something in your build process.
