### ISSUE TITLE
Template does not add on host 

### ISSUE THREAD

**Issue by Thiagott** [zabbix/zabbix-community-docker#98]
Hi,
I'm trying to add a new host but when I select the template to the specific host it does update. But once you see again on the host, the template is never added.
I tried take off the zabbix default template from the zabbix local host and once I tried put it again does not work as well.

any thoughts?

**Comment by jangaraj** [comment]
You have a problem with Zabbix UI. Unfortunately, Zabbix source code is not a part of this project => your problem is not in the scope of this project. I recommend reading Zabbix doc how to add a template to the host. I think you are not doing it properly.

https://github.com/monitoringartist/dockbix-xxl#support--issues
